CREATE TABLE tb_tutores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150),
    tipo_documento VARCHAR2(10),
    numero_documento VARCHAR2(30),
    data_nascimento DATE,
    email VARCHAR2(150),
    telefone VARCHAR2(30),
    tipo_responsavel VARCHAR2(30),
    preferencia_contato VARCHAR2(30),
    recebe_notificacao VARCHAR2(1),
    autoriza_monitoramento VARCHAR2(1),
    logradouro VARCHAR2(200),
    numero_endereco VARCHAR2(20),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    estado VARCHAR2(2),
    cep VARCHAR2(15),
    status VARCHAR2(20),
    data_cadastro TIMESTAMP,
    data_ultimo_acesso TIMESTAMP
);

CREATE TABLE tb_clinicas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150),
    cnpj VARCHAR2(30),
    email VARCHAR2(150),
    telefone VARCHAR2(30),
    logradouro VARCHAR2(200),
    numero_endereco VARCHAR2(20),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    estado VARCHAR2(2),
    cep VARCHAR2(15),
    status VARCHAR2(20),
    data_cadastro TIMESTAMP,
    tipo_estabelecimento VARCHAR2(100),
    especialidade_principal VARCHAR2(150),
    atendimento_24h VARCHAR2(1),
    atende_emergencia VARCHAR2(1)
);

CREATE TABLE tb_veterinarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150),
    crmv VARCHAR2(30),
    especialidade VARCHAR2(150),
    tipo_atuacao VARCHAR2(30),
    email VARCHAR2(150),
    telefone VARCHAR2(30),
    status VARCHAR2(20),
    data_cadastro TIMESTAMP,
    data_ultimo_acesso TIMESTAMP
);

CREATE TABLE tb_pets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsavel_id NUMBER NOT NULL,
    nome VARCHAR2(150),
    especie VARCHAR2(50),
    raca VARCHAR2(100),
    data_nascimento DATE,
    peso NUMBER(10,2),
    altura NUMBER(10,2),
    sexo VARCHAR2(1),
    porte VARCHAR2(30),
    status_saude VARCHAR2(100),
    alergias VARCHAR2(500),
    castrado VARCHAR2(1),
    cor_pelagem VARCHAR2(100),
    microchip VARCHAR2(100),
    data_cadastro TIMESTAMP,

    CONSTRAINT fk_pet_tutor
        FOREIGN KEY (responsavel_id)
        REFERENCES tb_tutores(id)
);

CREATE TABLE tb_consultas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsavel_id NUMBER NOT NULL,
    pet_id NUMBER NOT NULL,
    clinica_id NUMBER NOT NULL,
    veterinario_id NUMBER NOT NULL,
    data_criacao TIMESTAMP,
    data_prevista TIMESTAMP NOT NULL,
    retorno_previsto TIMESTAMP,
    tipo_consulta VARCHAR2(100),
    descricao_sintomas VARCHAR2(1000),
    diagnostico VARCHAR2(1000),
    status VARCHAR2(30),

    CONSTRAINT fk_consulta_tutor
        FOREIGN KEY (responsavel_id)
        REFERENCES tb_tutores(id),

    CONSTRAINT fk_consulta_pet
        FOREIGN KEY (pet_id)
        REFERENCES tb_pets(id),

    CONSTRAINT fk_consulta_clinica
        FOREIGN KEY (clinica_id)
        REFERENCES tb_clinicas(id),

    CONSTRAINT fk_consulta_veterinario
        FOREIGN KEY (veterinario_id)
        REFERENCES tb_veterinarios(id)
);